### ISSUE TITLE
New openhab-super-pom release

### ISSUE THREAD

**Issue by pfink** [openhab/infrastructure#15]
> Can you release a new openhab-super-pom with these changes @kaikreuzer?
> That would allow for using snapshot Maven plugin builds without having to build them locally.

_Originally posted by @wborn in https://github.com/openhab/infrastructure/issues/14#issuecomment-1169650449_

Btw, @kaikreuzer I found the Jenkins job https://ci.openhab.org/view/All/job/openhab-superpom/, but I think we never finished it. Should I delete the job or do we want to get it running (so that the job really does a release to Maven Central)?

**Comment by kaikreuzer** [comment]
I just published a new version 1.0.5.

Yes, I guess we never finished the job for it. Not sure what effort it would mean to make automatic publishing to Maven Central work. Doing it manually is fairly simple as I have everything set up locally.

**Comment by kaikreuzer** [comment]
@wborn fyi.

**Comment by pfink** [comment]
OK, I deleted the Jenkins job as it did not contain any signficant efforts and was just misleading.

**Comment by wborn** [comment]
Thanks @kaikreuzer!
It now downloads 3.4.0-SNAPSHOT when I run `mvn i18n:generate-default-translations` in an add-on bundle dir. :slightly_smiling_face:
