### ISSUE TITLE
Missing developer IDs result in bnd-maven-plugin warnings

### ISSUE THREAD

**Issue by wborn** [openhab/infrastructure#9]
The bnd-maven-plugin tries to use the developer information in the openhab-super-pom for deriving bundle manifest headers.

Apparently the POM is missing the developer IDs which results in lots of warnings that show in the Eclipse "Error Log" view:

![error-log](https://user-images.githubusercontent.com/12213581/58710100-dbb97c00-83bb-11e9-95e9-e694df3279ec.png)

The complete error message is:

`
Cannot consider developer in line '32' of file '/home/wouter/.m2/repository/org/openhab/openhab-super-pom/1.0.0/openhab-super-pom-1.0.0.pom' for bundle header 'Bundle-Developers' as it does not contain the mandatory id.`

Adding an `<id>` tag for each developer in the super POM will probably fix the warning. However that will probably also add Kai and Patrick as developers in the bundle manifest headers of each bundle.

What do you think would be the best solution?

See also:

* [Developers in openhab-super-pom](https://github.com/openhab/infrastructure/blob/de07850a121c754e6fde386c2ab34815d2de55de/pom.xml#L25-L38)
* [Developers (Maven POM Reference)](https://maven.apache.org/pom.html#Developers)
* [BndMavenPlugin.java code](https://github.com/bndtools/bnd/blob/aa80c6474da94fe4fbd3e50fc361c52a887fb3fe/maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java#L378-L404)
* [bnd issue for adding this logic](https://github.com/bndtools/bnd/issues/2447)

**Comment by pfink** [comment]
First, for understanding: We didn't intend to add the `developers` tag to the Super POM, but it was rejected when we tried to push it to Maven Central because of missing tags (`developers` was mentioned).

I think there are two clean ways of resolution:

- we remove the developers tag from this POM (I don't really understand why it's required for the Super POM and not for our other artifacts that are located in Maven Central)
- we add a developers tag on each inheriting POM reflecting the actual developers of the bundle

Everything else would be quite dirty in my eyes.

**Comment by kaikreuzer** [comment]
Hm, the good news of this issue is that bnd at least finds the super pom, while our Jenkins doesn't 🤔 ...

FTR, I added the developer section due to [this requirement](https://central.sonatype.org/pages/requirements.html#developer-information) of Sonatype for Maven Central uploads. Interestingly, their own example does not have any `id` element...

> not for our other artifacts that are located in Maven Central

@pfink Which artifacts do you refer to? The ones without any parent reference (like [this one](http://repo1.maven.org/maven2/org/openhab/tools/sat/pom/0.6.0/pom-0.6.0.pom)) should all have a developer section.

So afaik, removing the section is no option. Maintaining it throughout ALL our poms with correct information isn't imho an option either.
Maybe it works if we keep the section, but simply have an empty list of developers in it?

**Comment by pfink** [comment]
> Maybe it works if we keep the section, but simply have an empty list of developers in it?

I already tested this, but you need to add at least one (empty) developer to get the parent developers overriden. And then you would get the same warning according to the code of the bnd plugin.

> Maybe it works if we keep the section, but simply have an empty list of developers in it?

You're right, I didn't see that they still had a parent pom...

**Comment by wborn** [comment]
If the default merge behavior is causing troubles, you can maybe also use an empty developers section using `combine.self="override"` :

https://blog.sonatype.com/2011/01/maven-how-to-merging-plugin-configuration-in-complex-projects/

**Comment by pfink** [comment]
If you mean like this `<developers combine.self="override"/>`, it does not work.

**Comment by kaikreuzer** [comment]
Any further idea how we could deal with that?

**Comment by wborn** [comment]
I read `combine.self="override"` only works for `<configuration>` elements.

This is also an issue for CLI builds, see the [Jenkins console output](https://ci.openhab.org/job/openHAB-Core/217/consoleFull):

```
05:02:29 [INFO] --- bnd-maven-plugin:4.2.0:bnd-process (default) @ org.openhab.core.test ---
05:02:29 [WARNING] Cannot consider developer in line '26' of file '/var/jenkins_home/.m2/repository/org/openhab/openhab-super-pom/1.0.0/openhab-super-pom-1.0.0.pom' for bundle header 'Bundle-Developers' as it does not contain the mandatory id.
05:02:29 [WARNING] Cannot consider developer in line '32' of file '/var/jenkins_home/.m2/repository/org/openhab/openhab-super-pom/1.0.0/openhab-super-pom-1.0.0.pom' for bundle header 'Bundle-Developers' as it does not contain the mandatory id.
```

After looking at the bnd code, it only uses the POM elements if the `Bundle-Developers` is not already defined. So what works for me is adding a manifest entry to the [bnd-maven-plugin configuration](https://github.com/openhab/openhab-core/blob/9018e9ae80590c0f21e247d7ce31f21483b5e922/pom.xml#L152-L171). E.g. something like:

`Bundle-Developers: openhab; email=info@openhab.org; name="openHAB"; organization=openHAB; organizationUrl=https://www.openHAB.org`

You can also add roles and a timezone if that is important :smile: , see this [bnd file](https://github.com/bndtools/bnd/blob/ce090d4ad307a027633aaa879634a6803ca9c812/cnf/build.bnd#L45-L52).

**Comment by maggu2810** [comment]
How do you plan to move forward?
Any change to get this warnings removed again?

The [xsd](https://maven.apache.org/xsd/maven-4.0.0.xsd) states a min. occur of ID for developer of zero.

```xml
<xs:complexType name="Developer">
    <xs:annotation>
        ...
    </xs:annotation>
    <xs:all>
        <xs:element minOccurs="0" name="id" type="xs:string">
            ...
```

So, if Maven declares that option as optional and bnd complains that it is a mandatory field, I don't think we need to change the super POM (but I also consider an ID to be useful all the time e.g. for repositories you can blacklist one in childs using the ID etc.).

For openHAB bundles, I assume the suggestion of @wborn (using a hardcoded value in the plugin configuration to not use the POM attributes) is okay.

Another question is -- if the developer section is combined into the effective POM -- if it makes any sense that the current two stated developers are the ones that are present in every effective POM.

Can't we add the openHAB organization to the super POM as developers.
IMHO this is more correct for the effective POMs then the current situation.

**Comment by kaikreuzer** [comment]
> Can't we add the openHAB organization to the super POM as developers.

Sure, this is probably the best (and then also add an id to it to make bnd happy).
It just means we have to publish a new (patch) release of the super pom.

> if Maven declares that option as optional and bnd complains that it is a mandatory field

Sounds as if we should also file a bug to bnd, right?

**Comment by kaikreuzer** [comment]
> Sounds as if we should also file a bug to bnd, right?

Hm, apparently not as it states that [it is mandatory for OSGi](https://github.com/bndtools/bnd/blob/aa80c6474da94fe4fbd3e50fc361c52a887fb3fe/maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java#L378), while not for Maven.

**Comment by maggu2810** [comment]
> Sounds as if we should also file a bug to bnd, right?

If you use the bnd-maven-plugin to generate the manifest entries from POM entries (so, take the developers entries of the POM for bundle developers) it is IMHO not really a potential bug if the maven plugin requires that in that case the developer needs an ID (to get rid of a warning).
As @wborn already stated there will be no warning if you don't take that information of the POM.
Bug or not bug, it depends on the Bnd guys if their plugin needs it.

**Comment by kaikreuzer** [comment]
@maggu2810 & @wborn Can you confirm that https://github.com/openhab/infrastructure/pull/10 should fix the issue, once published to Maven Central?

**Comment by wborn** [comment]
The changes in #10 fix the warnings for me. :+1:
